In [1]:
2^2^1^1.3^1.5^1.7^20

4.0

In [2]:
3 & 5 > 0 

true

In [3]:
8 & 5 > 0

false

In [4]:
5040 / 60

84.0

In [7]:
? Cake

No documentation found.

Binding `Cake` does not exist.


search: catch_backtrace catch_stacktrace current_task

Couldn't find Cake
Perhaps you meant Core, Base, Date, base, take!, cat, Char, Cint, Cmd or asec


In [6]:
? \

```
\(x, y)
```

Left division operator: multiplication of `y` by the inverse of `x` on the left. Gives floating-point results for integer arguments.

```jldoctest
julia> 3 \ 6
2.0

julia> inv(3) * 6
2.0

julia> A = [1 2; 3 4]; x = [5, 6];

julia> A \ x
2-element Array{Float64,1}:
 -4.0
  4.5

julia> inv(A) * x
2-element Array{Float64,1}:
 -4.0
  4.5
```

```
\(A, B)
```

Matrix division using a polyalgorithm. For input matrices `A` and `B`, the result `X` is such that `A*X == B` when `A` is square. The solver that is used depends upon the structure of `A`.  If `A` is upper or lower triangular (or diagonal), no factorization of `A` is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular `A` the result is the minimum-norm least squares solution computed by a pivoted QR factorization of `A` and a rank estimate of `A` based on the R factor.

When `A` is sparse, a similar polyalgorithm is used. For indefinite matrices, the `LDLt` factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

# Example

```jldoctest
julia> A = [1 0; 1 -2]; B = [32; -4];

julia> X = A \ B
2-element Array{Float64,1}:
 32.0
 18.0

julia> A * X == B
true
```


search: \ .\



In [8]:
addone(x::Int64) = x+1

addone (generic function with 1 method)

In [9]:
addone(10)

11

In [10]:
a,b=1,2

a,b=b,a

(2, 1)

In [11]:
function test(input)
  println("$input"^2)
end

test(2)

22


In [12]:
add2(x,y) = x + y;
println(add2(5, 7))

12


In [13]:
add2(x,y) = return x + y
println(add2(5, 7))

12


In [14]:
function add2(x,y) = x + y
println(add2(5, 7))

LoadError: syntax: unexpected "="